import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import Footer from "@/components/footer";

const inter = Inter({subsets:["latin"]});

export const metadata = {
  title: "NextStep-AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{baseTheme:dark}}>

      <html lang="en" suppressHydrationWarning>
        <body
          className={`${inter.className}`}
          >
          <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
              >
              {/* header  */}
              <Header/>

              <main className="min-h-screen">{children}</main>

              {/* footer  */}
              
              <Footer/>
            </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
